version: '3'

services:
  django:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
