# Generated by Django 4.1.7 on 2023-04-08 15:07

from django.db import migrations, models
import django.db.models.deletion
import taxila.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomepageBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner_type",
                    models.CharField(choices=[("desktop", "desktop"), ("mobile", "mobile")], max_length=20),
                ),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inspiration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("main_image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InspirationCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KitchenCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KitchenItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_it", models.TextField(blank=True, null=True)),
                ("base_unit", models.TextField(blank=True, null=True)),
                ("wall_unit", models.TextField(blank=True, null=True)),
                ("tall_unit", models.TextField(blank=True, null=True)),
                ("design_solution", models.TextField(blank=True, null=True)),
                ("other", models.TextField(blank=True, null=True)),
                ("wall_unit_with_grip_recessed", models.BooleanField(default=False)),
                ("wall_unit_with_handle", models.BooleanField(default=False)),
                ("tall_unit_with_grip_recessed", models.BooleanField(default=False)),
                ("tall_unit_with_handle", models.BooleanField(default=False)),
                ("modular_base_unit", models.BooleanField(default=False)),
                ("living_room_base_unit", models.BooleanField(default=False)),
                ("tall_corner_walk_pantry", models.BooleanField(default=False)),
                ("tall_unit_with_extended_door", models.BooleanField(default=False)),
                ("hole_tall_unit", models.BooleanField(default=False)),
                ("modular_wall_unit", models.BooleanField(default=False)),
                ("living_and_open_box_unit", models.BooleanField(default=False)),
                ("sliding_counter", models.BooleanField(default=False)),
                ("boiserie", models.BooleanField(default=False)),
                ("glass_unit", models.BooleanField(default=False)),
                ("custom_on_request", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.kitchencategory"),
                ),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("main_image", models.FileField(blank=True, null=True, upload_to=taxila.models.upload_to_path)),
                ("name", models.CharField(max_length=255)),
                ("origin_country", models.CharField(blank=True, max_length=255, null=True)),
                ("level", models.PositiveBigIntegerField(default=0)),
                ("care_instruction", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("color", models.TextField(blank=True, null=True)),
                ("finish", models.TextField(blank=True, null=True)),
                ("application_countertops", models.BooleanField(default=False)),
                ("application_floorings", models.BooleanField(default=False)),
                ("application_walls", models.BooleanField(default=False)),
                ("application_shower", models.BooleanField(default=False)),
                ("application_fireplace", models.BooleanField(default=False)),
                ("application_outdoor", models.BooleanField(default=False)),
                ("technical_specification_petrographic_denomination", models.TextField(blank=True, null=True)),
                ("technical_specification_hardness", models.TextField(blank=True, null=True)),
                ("technical_specification_water_absorption", models.TextField(blank=True, null=True)),
                ("technical_specification_apparent_density", models.TextField(blank=True, null=True)),
                ("technical_specification_open_porosity", models.TextField(blank=True, null=True)),
                ("technical_specification_abrasion_strength", models.TextField(blank=True, null=True)),
                ("technical_specification_compressive_strength", models.TextField(blank=True, null=True)),
                ("technical_specification_attachement", models.FileField(upload_to=taxila.models.upload_to_path)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialVendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MetaData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=255, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("twitter_title", models.CharField(blank=True, max_length=255, null=True)),
                ("twitter_description", models.TextField(blank=True, null=True)),
                ("script", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("video_url", models.URLField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.videocategory")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(max_length=255)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.mediacategory")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("banner_image", models.FileField(blank=True, null=True, upload_to=taxila.models.upload_to_path)),
                ("sub_image", models.FileField(blank=True, null=True, upload_to=taxila.models.upload_to_path)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ("detail", models.TextField(blank=True, null=True)),
                ("feature_chip", models.PositiveIntegerField(default=0)),
                ("feature_heat", models.PositiveIntegerField(default=0)),
                ("feature_stain", models.PositiveIntegerField(default=0)),
                ("feature_scratch", models.PositiveIntegerField(default=0)),
                ("feature_water", models.PositiveIntegerField(default=0)),
                ("feature_frost", models.PositiveIntegerField(default=0)),
                ("pros", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.parentcategory"),
                ),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="taxila.materialcategory"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="vendor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="taxila.materialvendor"
            ),
        ),
        migrations.CreateModel(
            name="KitchenItemImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.kitchenitem")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="kitchencategory",
            name="parent_category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.parentcategory"),
        ),
        migrations.CreateModel(
            name="InspirationDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                (
                    "inspiration",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.inspiration"),
                ),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inspiration",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.inspirationcategory"),
        ),
    ]
