# Generated by Django 4.1.7 on 2023-02-24 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KitchenCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="KitchenItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("order", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_it", models.TextField(blank=True, null=True)),
                ("base_unit", models.TextField(blank=True, null=True)),
                ("wall_unit", models.TextField(blank=True, null=True)),
                ("tall_unit", models.TextField(blank=True, null=True)),
                ("design_solution", models.TextField(blank=True, null=True)),
                ("other", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.kitchencategory"),
                ),
            ],
            options={
                "ordering": ("ranking",),
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("images", models.TextField(blank=True, null=True)),
                ("origin_country", models.CharField(blank=True, max_length=255, null=True)),
                ("level", models.PositiveBigIntegerField(default=0)),
                ("care_instruction", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("color", models.TextField(blank=True, null=True)),
                ("finish", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialVendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialTechnicalSpecification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("petrographic_denomination", models.TextField(blank=True, null=True)),
                ("hardness", models.TextField(blank=True, null=True)),
                ("water_absorption", models.TextField(blank=True, null=True)),
                ("apparent_density", models.TextField(blank=True, null=True)),
                ("open_porosity", models.TextField(blank=True, null=True)),
                ("abrasion_strength", models.TextField(blank=True, null=True)),
                ("compressive_strength", models.TextField(blank=True, null=True)),
                ("attachement", models.FileField(upload_to="")),
                ("material", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
        ),
        migrations.CreateModel(
            name="MaterialImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("image", models.FileField(upload_to="")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
            options={
                "ordering": ("ranking",),
            },
        ),
        migrations.CreateModel(
            name="MaterialFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chip", models.TextField(blank=True, null=True)),
                ("heat", models.TextField(blank=True, null=True)),
                ("stain", models.TextField(blank=True, null=True)),
                ("scratch", models.TextField(blank=True, null=True)),
                ("water", models.TextField(blank=True, null=True)),
                ("frost", models.TextField(blank=True, null=True)),
                ("material", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
        ),
        migrations.CreateModel(
            name="MaterialApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("countertops", models.TextField(blank=True, null=True)),
                ("floorings", models.TextField(blank=True, null=True)),
                ("walls", models.TextField(blank=True, null=True)),
                ("shower", models.TextField(blank=True, null=True)),
                ("fireplace", models.TextField(blank=True, null=True)),
                ("outdoor", models.TextField(blank=True, null=True)),
                ("material", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="taxila.materialcategory"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="vendor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="taxila.materialvendor"
            ),
        ),
        migrations.CreateModel(
            name="KitchenItemImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("image", models.FileField(upload_to="")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.kitchenitem")),
            ],
            options={
                "ordering": ("ranking",),
            },
        ),
    ]
