# Generated by Django 4.1.7 on 2023-03-05 11:44

from django.db import migrations, models
import django.db.models.deletion
import taxila.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InspirationCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KitchenCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KitchenItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_it", models.TextField(blank=True, null=True)),
                ("base_unit", models.TextField(blank=True, null=True)),
                ("wall_unit", models.TextField(blank=True, null=True)),
                ("tall_unit", models.TextField(blank=True, null=True)),
                ("design_solution", models.TextField(blank=True, null=True)),
                ("other", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.kitchencategory"),
                ),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("origin_country", models.CharField(blank=True, max_length=255, null=True)),
                ("level", models.PositiveBigIntegerField(default=0)),
                ("care_instruction", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("color", models.TextField(blank=True, null=True)),
                ("finish", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialVendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MetaData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("og_title", models.CharField(blank=True, max_length=255, null=True)),
                ("twitter_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("twitter_description", models.TextField(blank=True, null=True)),
                ("script", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("video_url", models.URLField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.videocategory")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialTechnicalSpecification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("petrographic_denomination", models.TextField(blank=True, null=True)),
                ("hardness", models.TextField(blank=True, null=True)),
                ("water_absorption", models.TextField(blank=True, null=True)),
                ("apparent_density", models.TextField(blank=True, null=True)),
                ("open_porosity", models.TextField(blank=True, null=True)),
                ("abrasion_strength", models.TextField(blank=True, null=True)),
                ("compressive_strength", models.TextField(blank=True, null=True)),
                ("attachement", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("material", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chip", models.TextField(blank=True, null=True)),
                ("heat", models.TextField(blank=True, null=True)),
                ("stain", models.TextField(blank=True, null=True)),
                ("scratch", models.TextField(blank=True, null=True)),
                ("water", models.TextField(blank=True, null=True)),
                ("frost", models.TextField(blank=True, null=True)),
                ("material", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.parentcategory"),
                ),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("countertops", models.TextField(blank=True, null=True)),
                ("floorings", models.TextField(blank=True, null=True)),
                ("walls", models.TextField(blank=True, null=True)),
                ("shower", models.TextField(blank=True, null=True)),
                ("fireplace", models.TextField(blank=True, null=True)),
                ("outdoor", models.TextField(blank=True, null=True)),
                ("material", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="taxila.material")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="taxila.materialcategory"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="vendor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="taxila.materialvendor"
            ),
        ),
        migrations.CreateModel(
            name="KitchenItemImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.kitchenitem")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="kitchencategory",
            name="parent_category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.parentcategory"),
        ),
        migrations.CreateModel(
            name="Inspiration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("main_image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("sub_image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.inspirationcategory"),
                ),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
    ]
