# Generated by Django 4.1.7 on 2023-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxila", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
