# Generated by Django 4.2 on 2023-04-21 18:01

from django.db import migrations, models
import taxila.models


class Migration(migrations.Migration):
    dependencies = [
        ("taxila", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, null=True, upload_to=taxila.models.upload_to_path)),
                ("designation", models.CharField(blank=True, max_length=255, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("mail", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=255, null=True)),
                ("profile", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
    ]
