# Generated by Django 4.1.7 on 2023-03-26 11:17

from django.db import migrations, models
import django.db.models.deletion
import taxila.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxila", "0002_video_company_video_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspiration",
            name="sub_image",
        ),
        migrations.CreateModel(
            name="InspirationDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                (
                    "inspiration",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.inspiration"),
                ),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
    ]
