# Generated by Django 4.2 on 2023-04-22 07:55

from django.db import migrations, models
import taxila.models


class Migration(migrations.Migration):
    dependencies = [
        ("taxila", "0002_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("file", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
    ]
