# Generated by Django 4.2 on 2023-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxila", "0003_staticcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
