# Generated by Django 4.1.7 on 2023-03-26 12:54

from django.db import migrations, models
import taxila.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxila", "0003_remove_inspiration_sub_image_inspirationdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner_type",
                    models.CharField(choices=[("desktop", "desktop"), ("mobile", "mobile")], max_length=20),
                ),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inspirationcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="material",
            name="main_image",
            field=models.FileField(blank=True, null=True, upload_to=taxila.models.upload_to_path),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="banner_image",
            field=models.FileField(blank=True, null=True, upload_to=taxila.models.upload_to_path),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
