# Generated by Django 4.1.7 on 2023-03-26 13:34

from django.db import migrations, models
import django.utils.timezone
import taxila.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxila", "0004_homepagebanner_inspirationcategory_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="application_countertops",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="application_fireplace",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="application_floorings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="application_outdoor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="application_shower",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="application_walls",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_abrasion_strength",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_apparent_density",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_attachement",
            field=models.FileField(default=django.utils.timezone.now, upload_to=taxila.models.upload_to_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_compressive_strength",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_hardness",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_open_porosity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_petrographic_denomination",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="technical_specification_water_absorption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="feature_chip",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="feature_frost",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="feature_heat",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="feature_scratch",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="feature_stain",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="feature_water",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="pros",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="sub_image",
            field=models.FileField(blank=True, null=True, upload_to=taxila.models.upload_to_path),
        ),
        migrations.DeleteModel(
            name="MaterialFeature",
        ),
    ]
