# Generated by Django 4.2 on 2023-04-29 13:37

from django.db import migrations, models
import taxila.models


class Migration(migrations.Migration):
    dependencies = [
        ("taxila", "0004_media_content_alter_media_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="technical_specification_attachement",
            field=models.FileField(blank=True, null=True, upload_to=taxila.models.upload_to_path),
        ),
    ]
