# Generated by Django 4.2 on 2023-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxila", "0005_alter_material_technical_specification_attachement"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
