# Generated by Django 4.1.7 on 2023-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxila", "0005_material_application_countertops_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialtechnicalspecification",
            name="material",
        ),
        migrations.AddField(
            model_name="parentcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="MaterialApplication",
        ),
        migrations.DeleteModel(
            name="MaterialTechnicalSpecification",
        ),
    ]
