# Generated by Django 4.1.7 on 2023-03-29 16:08

from django.db import migrations, models
import django.db.models.deletion
import taxila.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxila", "0006_remove_materialtechnicalspecification_material_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ranking", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to=taxila.models.upload_to_path)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(max_length=255)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxila.mediacategory")),
            ],
            options={
                "ordering": ("ranking",),
                "abstract": False,
            },
        ),
    ]
