# Generated by Django 4.1.7 on 2023-03-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxila", "0007_mediacategory_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenitem",
            name="boiserie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="custom_on_request",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="glass_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="hole_tall_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="living_and_open_box_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="living_room_base_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="modular_base_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="modular_wall_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="sliding_counter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="tall_corner_walk_pantry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="tall_unit_with_extended_door",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="tall_unit_with_grip_recessed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="tall_unit_with_handle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="wall_unit_with_grip_recessed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kitchenitem",
            name="wall_unit_with_handle",
            field=models.BooleanField(default=False),
        ),
    ]
